ldap:
  enabled: false
  url: ldap://prodldap.opsmx.com:389
  userDnPattern: uid={0},ou=users,dc=opsmx,dc=com

spring:
  security:
    saml2:
      enabled: true
      relyingparty:
        registration:
          spinnaker:
            assertingparty:
              metadata-uri: https://dev-74845923.okta.com/app/exke80hm0sVF4heSV5d7/sso/saml/metadata
            signing:
              credentials:
              - private-key-location: file:/opt/saml/certs/key.pem
                certificate-location: file:/opt/saml/certs/cert.pem
      user-attribute-mapping:
        roles: memberOf

spinnaker:
  extensibility:
    plugins-root-path: /opt/spinnaker/plugins
    plugins:
      Armory.ObservabilityPlugin:
        enabled: true
        config:
          metrics:
            additionalTags:
              service: spin-gate
            prometheus:
              enabled: true
    repositories:
      pulumi:
        url: https://raw.githubusercontent.com/pulumi/spinnaker-plugins-repository/master/repositories.json
      armory-observability-plugin-releases:
        url: https://raw.githubusercontent.com/armory-plugins/armory-observability-plugin-releases/master/repositories.json 
management:
  metrics.distribution:
    percentiles[http.server.requests]: 0.95, 0.99
    percentiles-histogram[http.server.requests]: true
    sla[http.server.requests]: 300ms, 500ms
  endpoints.web:
    exposure.include: health,info,aop-prometheus
    management.endpoints.web.base-path: /
    path-mapping.prometheus: prometheus_metrics
  server.port: 8008
