spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasadops/apple-spin-cve.git
          username: prasadops
          password: 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
          basedir: /tmp/config-repo
          defaultLabel: main
